pipeline {
    agent {
        docker {
            image "maven 3.6.3-openjdk-17-slim"
            label "docker"
        }
    }


    stages {
        stage('Build') {
            steps {
               sh "mvn --version"
                sh 'mvn cacheable-data clean install'
            }
        }
    }
    post {
        always {
            cleanWs()
        }
    }
}